# Generated by Django 6.0.1 on 2026-02-03 06:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название аллергена')),
            ],
            options={
                'verbose_name': 'Аллерген',
                'verbose_name_plural': 'Аллергены',
            },
        ),
        migrations.CreateModel(
            name='CardBuys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meal_type', models.CharField(blank=True, choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=10)),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='ProductRemaining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('unit', models.CharField(default='кг', max_length=50, verbose_name='Единица измерения')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальное количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Остаток продукта',
                'verbose_name_plural': 'Остатки продуктов',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('meal_type', models.CharField(choices=[('select', 'Выберите'), ('breakfast', 'Завтрак'), ('lunch', 'Обед')], default='select', max_length=10, verbose_name='Тип приёма пищи')),
                ('ingredients', models.TextField(blank=True, null=True, verbose_name='Ингредиенты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыто')),
                ('allergens', models.ManyToManyField(blank=True, to='main.allergen', verbose_name='Аллергены')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('status', models.CharField(choices=[('pending', 'Готовится'), ('ready', 'Готов'), ('received', 'Получен')], default='pending', max_length=20, verbose_name='Статус')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.card', verbose_name='Блюдо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('chef', 'Chef'), ('admin', 'Admin')], max_length=20)),
                ('auto_redirect_to_home', models.BooleanField(default=False)),
                ('critical_allergens', models.ManyToManyField(blank=True, help_text='Блюда с этими аллергенами будут скрыты', related_name='critical_profiles', to='main.allergen', verbose_name='Критические аллергены')),
                ('liked_cards', models.ManyToManyField(blank=True, help_text='Блюда, отмеченные пользователем как понравившиеся', related_name='liked_by_profiles', to='main.card', verbose_name='Понравившиеся блюда')),
                ('non_critical_allergens', models.ManyToManyField(blank=True, help_text='Блюда с этими аллергенами будут отображаться с предупреждением', related_name='non_critical_profiles', to='main.allergen', verbose_name='Некритические аллергены')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
