# Generated by Django 6.0.1 on 2026-01-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Готовится'), ('ready', 'Готов'), ('received', 'Получен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
