# Generated by Django 6.0 on 2026-02-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuffetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('baked', 'Выпечка'), ('sweets', 'Сладости'), ('drinks', 'Напитки'), ('snacks', 'Закуски'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена')),
                ('ingredients', models.TextField(blank=True, verbose_name='Состав')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Количество в наличии')),
                ('allergens', models.ManyToManyField(blank=True, to='main.allergen', verbose_name='Аллергены')),
            ],
            options={
                'verbose_name': 'Буфетный товар',
                'verbose_name_plural': 'Буфетные товары',
                'ordering': ['category', 'name'],
            },
        ),
    ]
